apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-neo
spec:
 type: NodePort
 ports:
  - name: http
    protocol: TCP
    targetPort: 15672
    port: 15672
    nodePort: 32501
  - name: amqp
    protocol: TCP
    targetPort: 5672
    port: 5672
 selector:
  app: rabbitmq-neo
