# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth.proto',
  package='auth',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nauth.proto\x12\x04\x61uth\"\x1f\n\x08\x41uthArgs\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\" \n\x0eSuccessMessage\x12\x0e\n\x06isAuth\x18\x01 \x01(\x08\"\x1c\n\tLoginArgs\x12\x0f\n\x07tokenId\x18\x01 \x01(\t\"Z\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08photoURL\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0e\n\x06isAuth\x18\x05 \x01(\x08\x32\x62\n\x04\x41uth\x12\x30\n\x08\x61uthUser\x12\x0e.auth.AuthArgs\x1a\x14.auth.SuccessMessage\x12(\n\tloginUser\x12\x0f.auth.LoginArgs\x1a\n.auth.Userb\x06proto3'
)




_AUTHARGS = _descriptor.Descriptor(
  name='AuthArgs',
  full_name='auth.AuthArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accessToken', full_name='auth.AuthArgs.accessToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=51,
)


_SUCCESSMESSAGE = _descriptor.Descriptor(
  name='SuccessMessage',
  full_name='auth.SuccessMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isAuth', full_name='auth.SuccessMessage.isAuth', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=85,
)


_LOGINARGS = _descriptor.Descriptor(
  name='LoginArgs',
  full_name='auth.LoginArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tokenId', full_name='auth.LoginArgs.tokenId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=115,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='auth.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='auth.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='photoURL', full_name='auth.User.photoURL', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accessToken', full_name='auth.User.accessToken', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='auth.User.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isAuth', full_name='auth.User.isAuth', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=207,
)

DESCRIPTOR.message_types_by_name['AuthArgs'] = _AUTHARGS
DESCRIPTOR.message_types_by_name['SuccessMessage'] = _SUCCESSMESSAGE
DESCRIPTOR.message_types_by_name['LoginArgs'] = _LOGINARGS
DESCRIPTOR.message_types_by_name['User'] = _USER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthArgs = _reflection.GeneratedProtocolMessageType('AuthArgs', (_message.Message,), {
  'DESCRIPTOR' : _AUTHARGS,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.AuthArgs)
  })
_sym_db.RegisterMessage(AuthArgs)

SuccessMessage = _reflection.GeneratedProtocolMessageType('SuccessMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSMESSAGE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.SuccessMessage)
  })
_sym_db.RegisterMessage(SuccessMessage)

LoginArgs = _reflection.GeneratedProtocolMessageType('LoginArgs', (_message.Message,), {
  'DESCRIPTOR' : _LOGINARGS,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.LoginArgs)
  })
_sym_db.RegisterMessage(LoginArgs)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.User)
  })
_sym_db.RegisterMessage(User)



_AUTH = _descriptor.ServiceDescriptor(
  name='Auth',
  full_name='auth.Auth',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=209,
  serialized_end=307,
  methods=[
  _descriptor.MethodDescriptor(
    name='authUser',
    full_name='auth.Auth.authUser',
    index=0,
    containing_service=None,
    input_type=_AUTHARGS,
    output_type=_SUCCESSMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='loginUser',
    full_name='auth.Auth.loginUser',
    index=1,
    containing_service=None,
    input_type=_LOGINARGS,
    output_type=_USER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTH)

DESCRIPTOR.services_by_name['Auth'] = _AUTH

# @@protoc_insertion_point(module_scope)
