# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_processor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_processor.proto',
  package='data_processor',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x64\x61ta_processor.proto\x12\x0e\x64\x61ta_processor\"{\n\x0fInputParameters\x12\x0c\n\x04year\x18\x01 \x01(\t\x12\r\n\x05month\x18\x02 \x01(\t\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\t\x12\x0c\n\x04hour\x18\x04 \x01(\t\x12\x0b\n\x03min\x18\x05 \x01(\t\x12\x11\n\tlongitude\x18\x06 \x01(\t\x12\x10\n\x08latitude\x18\x07 \x01(\t\"N\n\x13ProcessedAttributes\x12\x19\n\x11\x62\x61se_reflectivity\x18\x01 \x01(\t\x12\x1c\n\x14\x62\x61se_radial_velocity\x18\x02 \x01(\t2m\n\x14\x44\x61taProcessorService\x12U\n\rgetAttributes\x12\x1f.data_processor.InputParameters\x1a#.data_processor.ProcessedAttributesb\x06proto3'
)




_INPUTPARAMETERS = _descriptor.Descriptor(
  name='InputParameters',
  full_name='data_processor.InputParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='data_processor.InputParameters.year', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='month', full_name='data_processor.InputParameters.month', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='day', full_name='data_processor.InputParameters.day', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hour', full_name='data_processor.InputParameters.hour', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min', full_name='data_processor.InputParameters.min', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='data_processor.InputParameters.longitude', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='data_processor.InputParameters.latitude', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=163,
)


_PROCESSEDATTRIBUTES = _descriptor.Descriptor(
  name='ProcessedAttributes',
  full_name='data_processor.ProcessedAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_reflectivity', full_name='data_processor.ProcessedAttributes.base_reflectivity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_radial_velocity', full_name='data_processor.ProcessedAttributes.base_radial_velocity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=243,
)

DESCRIPTOR.message_types_by_name['InputParameters'] = _INPUTPARAMETERS
DESCRIPTOR.message_types_by_name['ProcessedAttributes'] = _PROCESSEDATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputParameters = _reflection.GeneratedProtocolMessageType('InputParameters', (_message.Message,), {
  'DESCRIPTOR' : _INPUTPARAMETERS,
  '__module__' : 'data_processor_pb2'
  # @@protoc_insertion_point(class_scope:data_processor.InputParameters)
  })
_sym_db.RegisterMessage(InputParameters)

ProcessedAttributes = _reflection.GeneratedProtocolMessageType('ProcessedAttributes', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSEDATTRIBUTES,
  '__module__' : 'data_processor_pb2'
  # @@protoc_insertion_point(class_scope:data_processor.ProcessedAttributes)
  })
_sym_db.RegisterMessage(ProcessedAttributes)



_DATAPROCESSORSERVICE = _descriptor.ServiceDescriptor(
  name='DataProcessorService',
  full_name='data_processor.DataProcessorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=245,
  serialized_end=354,
  methods=[
  _descriptor.MethodDescriptor(
    name='getAttributes',
    full_name='data_processor.DataProcessorService.getAttributes',
    index=0,
    containing_service=None,
    input_type=_INPUTPARAMETERS,
    output_type=_PROCESSEDATTRIBUTES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAPROCESSORSERVICE)

DESCRIPTOR.services_by_name['DataProcessorService'] = _DATAPROCESSORSERVICE

# @@protoc_insertion_point(module_scope)
