apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nasa-cred
  namespace: default
spec:
  encryptedData:
    password: AgAEnyG6+CrK5difmAbYdur0Zy/eV2WxlH5xjWaEjuictdKw/N56jOT8x613T9uV7L+MP3dQREqh0e2JnkkI1qBBai2vtJNmN3l6qIE0wEKepJMBjiwN6K4mhlsxa7OuKwlBB3UNL7OOvdJxpa8Sklr5M4T7+wwPzNfPxjipZN8B6WKyfp98rLpH9a4VXtbGDKVk93VrVN0ScPjCunHq6FZHyiJJleY8a8fAu+NrgtalBModhOKMInP2bUnpf+k47qhi2qOk0qh75pJsyziJMOvye19Z8hW9lAjDsQXBRs8FuBPYtkLmHeb2DbpBDzp7YmFlgAvFltCuVe2nEzrgVhptBYIGE4KJSxnzf5wpF27DCKiO+6YZ7o8HP/Kc3NyX9z4gcW3tHZ4BONy00w2XBCeM8O+albW2g6X8B3EylO+HAfCoWmAlQPwyL48XnNwhR1VMj4gSrJCgmZrrh8Q4evRapMs00vcopF1jQPiYahqHf13+XjmUNAz0fNrM27+q0clgFN2OBL8n1iHlMbEJVtqFgHuBmyXvs1lwmYMw+MEjhBs3ed075sfsqnADya9yoG+9qcnwe5fk6v39mZhDiXSZ4Kbbft2jpKX17Zq4wJRkRjOgZ8K7LcIxAKI9SEkk2YJIcKv2hbEZgW8C0HVDdLPePncQ88j4MgVgrCAuCPXxBKAJa0KqrkHZX7bMbkRpDMND9yggptQnkx7G
    user: AgCi81JThIowSVmqR6fToXHGWLS55ZP5swREPhqI675zV3vX8KFnnLfbxS6YYsLohXP5uModKmgQ1J1GYOlJWs7qGBJwdOQT34ren8PxmjpScmyJdgoMTA66gZ+bOOS6MpeFNH+jw7SHkgUaXVDCGC4gW7uEiul8ITtmeBUQl8OA/hE2S+tm3w1ob2AYuFeKJpUzf4HmmQ3/N24rWDpyf8ERsvdSi5w5LuVnyTb5P62KHyh4P/d5eIgFZC4MENOtrBDqIOgpII+X2OE2qpulF8MjBLw55838Xr7LlA1sKugQbv6YOa2mbYsKYs1ikknwWdHeJkMPoj9H2ASirQmDjcy3BUAhXEe4BKWL8rak/CbsK0KoSd12mj0EtpYQyIkStUzCXnzb4i0zQwNfUxBj0vKrHZzcQaN0EuJ07KeBRE9+RG8AIyfUcvlX9zJUu8ZZDpvtssgRZVes8Sqx77kyIuQYAbYezO5yjVHeDEWAAbT+yQZjFxkNrv/fvBCHDjhISmpYDUUrAr0+AzTv2WLc9WvbN1bbOX57K5DNOc4YvqlM7qwPNQMbPCGt2Vh9PxG1Fq3WI5E2WnUqpU5FU+DxMgFoMDKI5uRSexngov5ArYJhCvJo6z4g/hQdV8ItXekou9OiZZyijbgFv7nQycB+T2axBIu+ULnGOk3eMOZoi9dfAoHOF5geLiGy1EDKlf1bC7K3ud//GgtSznV3/5YMULM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nasa-cred
      namespace: default
