# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_processor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_processor.proto',
  package='data_processor',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x64\x61ta_processor.proto\x12\x0e\x64\x61ta_processor\"v\n\nInputQuery\x12\x0c\n\x04year\x18\x01 \x01(\t\x12\r\n\x05month\x18\x02 \x01(\t\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\t\x12\x0c\n\x04hour\x18\x04 \x01(\t\x12\x0e\n\x06minute\x18\x05 \x01(\t\x12\x0f\n\x07\x66\x65\x61ture\x18\x06 \x01(\t\x12\x0f\n\x07station\x18\x07 \x01(\t\"#\n\x0bResultImage\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t2[\n\x14\x44\x61taProcessorService\x12\x43\n\x08getImage\x12\x1a.data_processor.InputQuery\x1a\x1b.data_processor.ResultImageb\x06proto3'
)




_INPUTQUERY = _descriptor.Descriptor(
  name='InputQuery',
  full_name='data_processor.InputQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='data_processor.InputQuery.year', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='month', full_name='data_processor.InputQuery.month', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='day', full_name='data_processor.InputQuery.day', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hour', full_name='data_processor.InputQuery.hour', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minute', full_name='data_processor.InputQuery.minute', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature', full_name='data_processor.InputQuery.feature', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='station', full_name='data_processor.InputQuery.station', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=158,
)


_RESULTIMAGE = _descriptor.Descriptor(
  name='ResultImage',
  full_name='data_processor.ResultImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_base64', full_name='data_processor.ResultImage.image_base64', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=195,
)

DESCRIPTOR.message_types_by_name['InputQuery'] = _INPUTQUERY
DESCRIPTOR.message_types_by_name['ResultImage'] = _RESULTIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputQuery = _reflection.GeneratedProtocolMessageType('InputQuery', (_message.Message,), {
  'DESCRIPTOR' : _INPUTQUERY,
  '__module__' : 'data_processor_pb2'
  # @@protoc_insertion_point(class_scope:data_processor.InputQuery)
  })
_sym_db.RegisterMessage(InputQuery)

ResultImage = _reflection.GeneratedProtocolMessageType('ResultImage', (_message.Message,), {
  'DESCRIPTOR' : _RESULTIMAGE,
  '__module__' : 'data_processor_pb2'
  # @@protoc_insertion_point(class_scope:data_processor.ResultImage)
  })
_sym_db.RegisterMessage(ResultImage)



_DATAPROCESSORSERVICE = _descriptor.ServiceDescriptor(
  name='DataProcessorService',
  full_name='data_processor.DataProcessorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=197,
  serialized_end=288,
  methods=[
  _descriptor.MethodDescriptor(
    name='getImage',
    full_name='data_processor.DataProcessorService.getImage',
    index=0,
    containing_service=None,
    input_type=_INPUTQUERY,
    output_type=_RESULTIMAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAPROCESSORSERVICE)

DESCRIPTOR.services_by_name['DataProcessorService'] = _DATAPROCESSORSERVICE

# @@protoc_insertion_point(module_scope)
