# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_processor_pb2 as data__processor__pb2


class DataProcessorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAttributes = channel.unary_unary(
                '/data_processor.DataProcessorService/getAttributes',
                request_serializer=data__processor__pb2.InputParameters.SerializeToString,
                response_deserializer=data__processor__pb2.ProcessedAttributes.FromString,
                )


class DataProcessorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataProcessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.getAttributes,
                    request_deserializer=data__processor__pb2.InputParameters.FromString,
                    response_serializer=data__processor__pb2.ProcessedAttributes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data_processor.DataProcessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataProcessorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data_processor.DataProcessorService/getAttributes',
            data__processor__pb2.InputParameters.SerializeToString,
            data__processor__pb2.ProcessedAttributes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
