apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-creds
  namespace: default
spec:
  encryptedData:
    password: AgCJ4BpNqcnp0a8zqVBobrwGjNBb+nwzI36KCKfoIhwpZSEOSPldpZQGgzLT/A/AWL0BARlzAQnC4rhPn9Ao494ZpjDw1BmLrstPOSEVYyOPTwuGJVYCmWDf5+ElnRlFrbXvqcfxr9WKJMq+OsprJkm6nTjz9dPl0VdOpijjwlJxrF4qbJ5NquJ5q8fhOcoZVn24VxDnXuoZqN6J0Vv0T3BrFTXaUfWrb8z4fk8V1BoBNJa08HDzJfJzTxMn4gHfFEjjHQE0AFiiqrauZHb4lAAVZQcdpV9Wfw5XMf+dMwIN4MPIbVEhgRDMwN3s4txXhscQViPeEv2CkvWXmMHz1FKiLXsFhUWJy0tooZBxYgCBBenEPbXu/6gnyXPJa+70YT66Duq6sVqCyWxlPTEOiQgCa3C0eSNWOwZqG7SwdFx9lpyQfVbIav5Pie227Ano1XI2NyIQYwIbYmwbasQjSPL63Xbj8OdvNq9ElxwfXddCdds4F/K2Vlh597IE2Htuvd30k1enR1xQpbNL1QbsaEa/+8SxpPLzbov8zNrbz3fPtWc+jZXJZOYDZD/qT3CJf+jJh2Dedy3voVIsqdu0CHjAXgpZcJHFXdoH/iW+MGpeVOjekP8wOeDhbo8IXijppM1g0sD9mmZl4GRVqpTdNdaBWO5jkkiUwGVar9mQTHHtdsvrlw+Y2Q3324N4x6c3z3/VSld1yaRxQA==
    username: AgB5rhCcwtmzuAP+8+xTmx0nQMZhFuTIUqlNYPABamLpY8CWovFlr+n3fLrTlKHnssbElPDnYsB24rsE2IcaL4YxsLcMf53m0F0ogDZ6xjLo6NsYNh7b3fytw6sRql3ZiT2Hs1RpBJV9xq8Oj+HPcETJobSnWleMivRspJREsIeGZRbTPeclptRzWXxle6H8iorSRaRKkSVofeHrB25SI7VQsBVpdoTtxebUyQkqcw6gu9otw/p4019fZtFwSCrgNB4AgTP/+ie86kxBWwrNOoUtlDWc35Cn6cwSN7OcEhaZdjXkNR3ViBZLMqPLNk3eKYQTfA1f49S9PTLDtUGjzE395MUm0qYIxLQpAZPZYbSC5ycZ1BKHTBuv3D8PsnRcbHHs4GfbXw8pKxetwvkDvj/jsCwcGjfgjs7BYQhZ4phVGFJtZeXAUJ7fMyk4UTBOfaFkeWxUiD7jamtsvPUmV9KDsTfzMGw3XJrSMgrzWS+v6n9QDir/Hb4dpYtRFDbKNfLvlwOWfoGil/ubScw7Ow4LmTBPJHyWqlyWKAHFc1rC4SMSHA3RAGDVJWwSBaj8q03fUMYf7XAGjbQy01b/Wlue/h3lU0cu/3xIAg2sBWGyIv+DmvA/Z4ruDRPUmfy4rgEJ/47tDeKgFA3HNzuRTd9GlIdKPgYsX7MneWhHvWe5xG5s7JGNJVcwJjys4sgRzjSNiq7A
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongo-creds
      namespace: default