apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: gateway

    spec:
      containers:
      - name: gateway
        imagePullPolicy: Always
        image: neoairavataproject/gateway:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8081
      restartPolicy: Always