# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import registry_pb2 as registry__pb2


class RegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registerWidget = channel.unary_unary(
                '/registry.Registry/registerWidget',
                request_serializer=registry__pb2.Widget.SerializeToString,
                response_deserializer=registry__pb2.SuccessMessage.FromString,
                )
        self.getHistory = channel.unary_unary(
                '/registry.Registry/getHistory',
                request_serializer=registry__pb2.HistoryArgs.SerializeToString,
                response_deserializer=registry__pb2.History.FromString,
                )


class RegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def registerWidget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registerWidget': grpc.unary_unary_rpc_method_handler(
                    servicer.registerWidget,
                    request_deserializer=registry__pb2.Widget.FromString,
                    response_serializer=registry__pb2.SuccessMessage.SerializeToString,
            ),
            'getHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.getHistory,
                    request_deserializer=registry__pb2.HistoryArgs.FromString,
                    response_serializer=registry__pb2.History.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'registry.Registry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Registry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def registerWidget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/registry.Registry/registerWidget',
            registry__pb2.Widget.SerializeToString,
            registry__pb2.SuccessMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/registry.Registry/getHistory',
            registry__pb2.HistoryArgs.SerializeToString,
            registry__pb2.History.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
