---
- name: Check ansible version
  import_playbook: ansible_version.yml

- hosts: kube-master[0]
  gather_facts: no
  roles:
    - { role: kubespray-defaults }
    - { role: bootstrap-os, tags: bootstrap-os }
    - { role: remove-node/pre-remove, tags: pre-remove }

- hosts: "{{ node | default('kube-node') }}"
  gather_facts: no
  roles:
    - { role: kubespray-defaults, when: reset_nodes|default(True)|bool }
    - { role: bootstrap-os, tags: bootstrap-os, when: reset_nodes|default(True)|bool }
    - { role: remove-node/remove-etcd-node }
    - { role: reset, tags: reset, when: reset_nodes|default(True)|bool }

# Currently cannot remove first master or etcd
- hosts: "{{ node | default('kube-master[1:]:etcd[1:]') }}"
  gather_facts: no
  roles:
    - { role: kubespray-defaults, when: reset_nodes|default(True)|bool }
    - { role: bootstrap-os, tags: bootstrap-os, when: reset_nodes|default(True)|bool }
    - { role: remove-node/post-remove, tags: post-remove }
