# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth.proto',
  package='authentication',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nauth.proto\x12\x0e\x61uthentication\"8\n\rSampleRequest\x12\x12\n\nmy_request\x18\x01 \x01(\t\x12\x13\n\x0bmy_req_data\x18\x02 \x01(\t\";\n\x0eSampleResponse\x12\x13\n\x0bmy_response\x18\x01 \x01(\t\x12\x14\n\x0cmy_resp_data\x18\x02 \x01(\t2]\n\x0b\x41uthService\x12N\n\rgetSampleData\x12\x1d.authentication.SampleRequest\x1a\x1e.authentication.SampleResponseb\x06proto3'
)




_SAMPLEREQUEST = _descriptor.Descriptor(
  name='SampleRequest',
  full_name='authentication.SampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='my_request', full_name='authentication.SampleRequest.my_request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='my_req_data', full_name='authentication.SampleRequest.my_req_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=86,
)


_SAMPLERESPONSE = _descriptor.Descriptor(
  name='SampleResponse',
  full_name='authentication.SampleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='my_response', full_name='authentication.SampleResponse.my_response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='my_resp_data', full_name='authentication.SampleResponse.my_resp_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['SampleRequest'] = _SAMPLEREQUEST
DESCRIPTOR.message_types_by_name['SampleResponse'] = _SAMPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleRequest = _reflection.GeneratedProtocolMessageType('SampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:authentication.SampleRequest)
  })
_sym_db.RegisterMessage(SampleRequest)

SampleResponse = _reflection.GeneratedProtocolMessageType('SampleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLERESPONSE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:authentication.SampleResponse)
  })
_sym_db.RegisterMessage(SampleResponse)



_AUTHSERVICE = _descriptor.ServiceDescriptor(
  name='AuthService',
  full_name='authentication.AuthService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=149,
  serialized_end=242,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSampleData',
    full_name='authentication.AuthService.getSampleData',
    index=0,
    containing_service=None,
    input_type=_SAMPLEREQUEST,
    output_type=_SAMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHSERVICE)

DESCRIPTOR.services_by_name['AuthService'] = _AUTHSERVICE

# @@protoc_insertion_point(module_scope)
