---
# https://download.docker.com/linux/debian/
docker_versioned_pkg:
  'latest': docker-ce
  '18.09': docker-ce=5:18.09.9~3-0~debian-{{ ansible_distribution_release|lower }}
  '19.03': docker-ce=5:19.03.14~3-0~debian-{{ ansible_distribution_release|lower }}
  '20.10': docker-ce=5:20.10.2~3-0~debian-{{ ansible_distribution_release|lower }}
  'stable': docker-ce=5:19.03.14~3-0~debian-{{ ansible_distribution_release|lower }}
  'edge': docker-ce=5:19.03.14~3-0~debian-{{ ansible_distribution_release|lower }}

docker_cli_versioned_pkg:
  'latest': docker-ce-cli
  '18.09': docker-ce-cli=5:18.09.9~3-0~debian-{{ ansible_distribution_release|lower }}
  '19.03': docker-ce-cli=5:19.03.14~3-0~debian-{{ ansible_distribution_release|lower }}
  '20.10': docker-ce-cli=5:20.10.2~3-0~debian-{{ ansible_distribution_release|lower }}

docker_package_info:
  pkg_mgr: apt
  pkgs:
    - name: "{{ containerd_versioned_pkg[containerd_version | string] }}"
      force: yes
    - name: "{{ docker_cli_versioned_pkg[docker_cli_version | string] }}"
      force: yes
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
      force: yes

docker_repo_key_info:
  pkg_key: apt_key
  url: '{{ docker_debian_repo_gpgkey }}'
  repo_keys:
    - 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

docker_repo_info:
  pkg_repo: apt_repository
  repos:
    - >
      deb {{ docker_debian_repo_base_url }}
      {{ ansible_distribution_release|lower }}
      stable
