---
# https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package
# https://download.docker.com/linux/centos/<centos_version>>/x86_64/stable/Packages/
# or do 'yum --showduplicates list docker-engine'
docker_versioned_pkg:
  'latest': docker-ce
  '18.09': docker-ce-18.09.9-3.el7
  '19.03': docker-ce-19.03.14-3.el{{ ansible_distribution_major_version }}
  '20.10': docker-ce-20.10.2-3.el{{ ansible_distribution_major_version }}
  'stable': docker-ce-19.03.14-3.el{{ ansible_distribution_major_version }}
  'edge': docker-ce-19.03.14-3.el{{ ansible_distribution_major_version }}

docker_cli_versioned_pkg:
  'latest': docker-ce-cli
  '18.09': docker-ce-cli-18.09.9-3.el7
  '19.03': docker-ce-cli-19.03.14-3.el{{ ansible_distribution_major_version }}
  '20.10': docker-ce-cli-20.10.2-3.el{{ ansible_distribution_major_version }}

docker_package_info:
  pkg_mgr: yum
  pkgs:
    - name: "{{ containerd_versioned_pkg[containerd_version | string] }}"
      repo: "docker-ce"
    - name: "{{ docker_cli_versioned_pkg[docker_cli_version | string] }}"
      repo: "docker-ce"
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
      repo: "docker-ce"

docker_repo_key_info:
  pkg_key: ''
  repo_keys: []

docker_repo_info:
  pkg_repo: ''
  repos: []
