apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deploy
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 3
  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
      - name: auth-service
        imagePullPolicy: Always
        image: neoairavataproject/auth-service:3.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 43000
      restartPolicy: Always
